services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "11"
      DISK_SIZE: "64G"
      RAM_SIZE: "2.2G"
      CPU_CORES: "3"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./macos:/storage
    restart: always
    stop_grace_period: 2m
